version: "3"
services:
  api:
    build:
      context: ./api
    container_name: silvercord-api
    env_file:
      - ./api/.env.local
    ports:
      - "8080:8080"
    restart: always

  agent:
    build:
      context: ./silvercord_agent
    container_name: silvercord-agent
    env_file:
      - ./silvercord_agent/.env
    depends_on:
      - api
    restart: always

  discord-bot:
    build:
      context: .
    container_name: silvercord-discord
    env_file:
      - ./.env
    depends_on:
      - api
    restart: always

  discord-deploy:
    build:
      context: .
    container_name: silvercord-discord-deploy
    command: node src/deploy_commands.js
    env_file:
      - ./.env
    restart: "no"

  agent-setup:
    build:
      context: ./silvercord_agent
    container_name: silvercord-agent-setup
    command: python db_store.py
    env_file:
      - ./silvercord_agent/.env
    restart: "no"

